file_format: "1"
id: clickyclacky
name: ClickyClacky
type: shield
url: https://github.com/ctefer/zmk-config-clickyclacky
requires:
  - nice_nano_v2
features:
  - keys
siblings:
  - clicklyclacky_left
  - clicklyclacky_right